/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_themassacre_minegame_Utils */

#ifndef _Included_org_themassacre_minegame_Utils
#define _Included_org_themassacre_minegame_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_themassacre_minegame_Utils
 * Method:    computeHashNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_themassacre_minegame_Utils_computeHashNative
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
